### CONFIG PARAMETERS FOR YAML CONFIG FILE ###

KEY_COVERAGE = "coverage"

KEY_COVERAGE_WORKSPACE = "workspace"
KEY_COVERAGE_PRIVATE_WORKSPACE = "private"
KEY_COVERAGE_PRIVATE_HEATMAPS = "heatmaps"
KEY_COVERAGE_COVERAGE_CURRENT_TAB = "current_tab"
KEY_COVERAGE_CURRENT_TRACKED_DATA = "tracked"

KEY_COVERAGE_RECORDED_POINTS = "recorded_points"
KEY_COVERAGE_RECORDED_POINTS_X = "x"
KEY_COVERAGE_RECORDED_POINTS_Y = "y"
KEY_COVERAGE_RECORDED_POINTS_DATA = "data"
KEY_COVERAGE_RECORDED_POINTS_DATA_SSID = "ssid"
KEY_COVERAGE_RECORDED_POINTS_DATA_RSSI = "rssi"
