from app_util.app_util import resource_path

### Main App parameters ###
WORKSPACE_FOLDER = r'workspace'
PRIVATE_FOLDER = r'workspace\cached'

APP_HEIGHT = 800
APP_WIDTH = 1500
APP_TITLE = "Citrus"
APP_ICO_PATH = resource_path("assets/seedling.ico")
APP_THEME = 'sandstone'

PROJECT_NEW = "NEW"
PROJECT_LOAD = "LOAD"
INTERFACE_WIFI = "WIFI CHIP"
INTERFACE_SDR = "LIMESDR MINI"
INTERFACE_LIST = (INTERFACE_WIFI, INTERFACE_SDR)

MODE_SPECTRUM_ANALYZER = "Spectrum Mode"
MODE_RECORDING = "Recording Mode"
MODE_COVERAGE = "Coverage Mode"
MODE_REPLAY = "Replay Mode"

SPECTRUM_PLOT_TITLE = "Spectrum Analyzer"
SPECTRUM_PLOT_LEGEND_X = "Frequency"
SPECTRUM_PLOT_LEGEND_Y = "Signal Strength"
SPECTRUM_PLOT_UNITS_PREFIX_MEGA_X = "M"
SPECTRUM_PLOT_UNITS_PREFIX_KILO_X = "K"
SPECTRUM_PLOT_UNITS_PREFIX_GIGA_X = "G"
SPECTRUM_PLOT_UNITS_POSTFIX_X = "Hz"
SPECTRUM_PLOT_UNITSD_Y = "Signal Strength"

CANVAS_HEIGHT = 800
CANVAS_WIDTH = 1200

POINT_KEY_TK_X = 'tk_x'
POINT_KEY_TK_Y = 'tk_y'
POINT_KEY_WIFI_DATA = 'wifi_data'

HEATMAP_PLOT_X = 'x'
HEATMAP_PLOT_Y = 'y'
HEATMAP_PLOT_SIGNAL = 'rssi'

WATERFALL_PLOT_LEGEND_X = 'freq_bins'
WATERFALL_PLOT_LEGEND_Y = 'timestamps'
WATERFALL_PLOT_LEGEND_Z = 'strength'
